clc;
clear all;
close all;
fs = 2e3;
specs = abs(input("Enter the filter passband and stopband attenuation"));
freq_pass = input("Enter the passband frequencies")/(fs/2);
freq_stop = input("Enter the stopband frequencies")/(fs/2);
[n, wc] = cheb1ord(freq_pass, freq_stop, specs(1), specs(2));
[b, a] = cheby1(n, specs(1), wc, "bandpass");
freqz(b, a);
L = input("Enter the length of the signal: ");
t = (0:L-1).*(1/fs);
s = 2.45*cos(2*pi*120*t) + 2*randn(size(t)) + 8.9*sin(2*pi*50*t);
y_new = filter(b, a, s);
figure(2);
subplot(1, 2, 1);
stem(1000*t, s);
xlabel("Time(milliseconds)")
ylabel("Amplitude of the signal");
subplot(1, 2, 2);
stem(1000*t, y_new);
xlabel("Time(milliseconds)")
ylabel("Amplitude of the filtered signal");
s_fft = fft(s, L);
y_new_fft = fft(y_new, L);
figure(3);
subplot(2, 2, 1);
plot(fs/L*(-L/2:L/2-1), abs(fftshift(s_fft)));
xlabel("F (Hz)");
ylabel("Mag of the noisy signal");
subplot(2, 2, 2);
plot(fs/L*(-L/2:L/2-1), abs(fftshift(y_new_fft)));
xlabel("F (Hz)");
ylabel("Mag of the filtered signal");
subplot(2, 2, 3);
plot(fs/L*(-L/2:L/2-1), unwrap(angle(fftshift(s_fft))));
xlabel("F (Hz)");
ylabel("Phase of the noisy signal");
subplot(2, 2, 4);
plot(fs/L*(-L/2:L/2-1), unwrap(angle(fftshift(y_new_fft))));
xlabel("F (Hz)");
ylabel("Phase of the filtered signal");